version: '3'

services:
  backend:
    container_name: BACKEND
    restart: always
    build: ./BACKEND
    ports:
      - "3000:3000"
    networks:
      - default1

  

networks:
  default1:
         