version: '3'

services:
  backend:
    container_name: BACKEND
    restart: always
    build: ./BACKEND
    ports:
      - "3001:3001"
    networks:
      - default1

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "4000:4000"
    networks:
      - default1

  

networks:
  default1:
         